### ISSUE TITLE
[BUG/ERROR] Fatal Error with analyze mode for specific files

### ISSUE THREAD

**Issue by James-Njoroge** [forrestdavis/NLPScholar#12]
## Describe the bug

While running analyze mode with 4 separate instances, we get a fatal dataframe error below: 
```shell
(nlp) user@s03:~/pbs$ python ../nlp/NLPScholar/main.py '../nlp/nlp-midterm/data/ru_data/obj_rel_across_anim_ru.yaml'
Reading from ../nlp/nlp-midterm/data/ru_data/obj_rel_across_anim_ru.yaml
all
Traceback (most recent call last):
  File "/home/user/pbs/../nlp/NLPScholar/main.py", line 34, in <module>
    exp.analyze()
  File "/home/user/nlp/NLPScholar/src/analysis/MinimalPair.py", line 196, in analyze
    by_pair = self.summarize_roi(by_word)
  File "/home/user/nlp/NLPScholar/src/analysis/MinimalPair.py", line 94, in summarize_roi
    target['mapping'] = target.apply(lambda x: {curr:new for new, curr in enumerate(x['ROI'])}, axis=1)
  File "/home/user/.conda/envs/nlp/lib/python3.10/site-packages/pandas/core/frame.py", line 4301, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/user/.conda/envs/nlp/lib/python3.10/site-packages/pandas/core/frame.py", line 4459, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column mapping
```

## To Reproduce

- Activate your 'nlp' environment.

- Run the input file in the evaluate mode. 

- Run the analyze mode on your input file and predictions file.

- Use this config: 
```Python 
exp: MinimalPair

mode: 
    - analyze

models: 
      hf_masked_model:
          - google-bert/bert-base-multilingual-cased

datafpath: ../nlp/nlp-midterm/data/ru_data/obj_rel_across_anim_ru.tsv

predfpath: ../nlp/nlp-midterm/predictions/multi/ru/obj_rel_across_anim_ru.tsv

resultsfpath: ../nlp/nlp-midterm/results/multi/ru/obj_rel_across_anim_ru.tsv

batchSize: 16
```

- The .tsv file with the initial data is [here](https://drive.google.com/file/d/1PGhCQlbHEZnB9tzJ45SVkbbqkd0hwGP7/view?usp=sharing)

## Expected behavior

Fatal error related to DataFrame mapping.

## Observed behavior 

It accepted and read the config file but gave a fatal error.

## Screenshots 

Error already pasted in the first part

## Setup (please complete the following information)
 - OS: Turing in 'nlp' environment.

## Additional context

N/A

**Comment by grushaprasad** [comment]
This seems to be an issue with your ROI specification where your ROI is always 6, but it looks like there might not be 6 words in the sentence. If you consider a smaller version of your file with just the first 16 sentences, and changed ROI to something like 3, the error goes away and expected files get generated. 
[obj_rel_across_anim_ru_small.txt](https://github.com/user-attachments/files/17372587/obj_rel_across_anim_ru_small.txt)
