### ISSUE TITLE
[BUG/ERROR] Parse Error when Tokenizing Training Dataset

### ISSUE THREAD

**Issue by yimeng-blake** [forrestdavis/NLPScholar#13]
## Describe the bug

I'm having trouble training the masked language model distilbert/distilbert_base_cased. The error message looks like this:
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 1034, saw 7

## To Reproduce

1. Download all relevant files, create two directories, one called 'hw2_configs" and the other 'hw2_files'
2. Drag relevant files into respective folders, .txt files go into hw2_files, .yaml files go into hw2_configs
[neg_train_train.txt](https://github.com/user-attachments/files/17513549/neg_train_train.txt)
[neg_train_val.txt](https://github.com/user-attachments/files/17513550/neg_train_val.txt)
[pos_train_train.txt](https://github.com/user-attachments/files/17513553/pos_train_train.txt)
[pos_train_val.txt](https://github.com/user-attachments/files/17513555/pos_train_val.txt)

It seems that I can't upload .yaml files, so I'll just paste the contents here:
For training the positive model (titled train_pos.yaml)l:
exp: TextClassification

mode:
    - train

models: 
      hf_masked_model:
          - distilbert/distilbert-base-cased

trainfpath: hw2_files/pos_train_train.txt
validfpath: hw2_files/pos_train_val.txt
modelfpath: imdb_pos_model

epochs: 1

For training the negative model (titled train_neg.yaml)l:
exp: TextClassification

mode:
    - train

models: 
      hf_masked_model:
          - distilbert/distilbert-base-cased

trainfpath: hw2_files/neg_train_train.txt
validfpath: hw2_files/neg_train_val.txt
modelfpath: imdb_neg_model

epochs: 1

3. conda activate nlp, then run the config files

python main.py hw2_configs/train_neg.yaml
python main.py hw2_configs/train_pos.yaml

5. See error

## Expected behavior

The tokenizer should not recognize more than 1 field for the data, training should go smoothly.

## Observed behavior 

The model run into error while generating test split, saying error tokenizing data and expected less fields than actually observed.

## Screenshots 

Here are the screenshots with errors on both config files:
<img width="1266" alt="Screenshot 2024-10-24 at 18 30 26" src="https://github.com/user-attachments/assets/459782f5-c9fd-4a40-be64-278a43ba143a">
<img width="1276" alt="Screenshot 2024-10-24 at 18 30 42" src="https://github.com/user-attachments/assets/46aab0d8-c247-4407-9961-1fad2c840763">

## Setup (please complete the following information)
 - OS: MacOS

**Comment by forrestdavis** [comment]
Thanks for posting an issue. 

A few things: 

- Your data needs to have a header `text`
- You should drop the bad rows. An easy way to do this is with the script below. It loads all the files in your `hw2_files` directory, loads them dropping the bad rows, and then saves them with the same name: 

```python
import pandas as pd
import glob

for fname in glob.glob('hw2_files/*'):
    data = pd.read_csv(fname, sep='\t', on_bad_lines='skip')
    data.to_csv(fname, sep='\t', index=False)
```

**Comment by forrestdavis** [comment]
Also as mentioned before the exp should be MinimalPair. Those changes should get your model going
