### ISSUE TITLE
[BUG/ERROR] group_texts Function Crashes on Non-List Data

### ISSUE THREAD

**Issue by Jaanhvi18** [forrestdavis/NLPScholar#17]
## **Describe the Bug**
The `group_texts` function in the `HFLanguageModelTrainer` class crashes when input data (`examples`) contains non-list elements, such as integers. The issue arises during the concatenation step, where it assumes all elements in `examples` are lists. This causes a `TypeError`.

## **To Reproduce**
1. Use a dataset where one or more keys in the `examples` dictionary contain integers or other non-list types.
2. Call the `group_texts` function with the dataset.
3.  error message:
   ```
   TypeError: can only concatenate list (not "int") to list
   ```

---

## **Expected Behavior**
The function should handle all elements in `examples` gracefully by:
1. normalizing non-list elements (e.g., wrapping integers in single-element lists).

---

## **Observed Behavior**
The function crashes with a `TypeError`:
```
TypeError: can only concatenate list (not "int") to list
```

## **Setup**
- **OS:** turing
- **Python Version:** 3.10
- **Libraries:** 
  - `datasets` (latest version)
  - `transformers` (latest version)

---

## **Additional Context**
The problematic line in the current function:
```python
concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
```

This assumes all values in `examples` are lists, leading to failure when it sees ints or non-list types.

### **Suggested Fix**

```python
    def group_texts(self, examples):
        # before processing the data, everything in examples is treated like a list. If the code finds a single number or something else, it wraps it in a list
        concatenated_examples = {
            k: sum(
                (v if isinstance(v, list) else [v] for v in examples.get(k, [])), []
            )
            for k in examples.keys()
        }

        # if any part of the data is missing or empty, the code will stop 
        if not all(isinstance(v, list) and len(v) > 0 for v in concatenated_examples.values()):
            raise ValueError("All keys in examples must map to non-empty lists.")

        # Determine the total length for splitting
        total_length = len(concatenated_examples[list(examples.keys())[0]])

        # Split into chunks of maxSequenceLength  even if the input data isn’t perfect.
        result = {
            k: [t[i : i + self.maxSequenceLength] for i in range(0, total_length, self.maxSequenceLength)]
            for k, t in concatenated_examples.items()
        }

        return result
```

**Comment by forrestdavis** [comment]
you don't need a `textid` column
